---
# see https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml

autoDiscovery:
  clusterName: ${eks_cluster_name}
awsRegion: ${aws_region} 
nodeSelector:
  #cluster-autoscaler is system component and should only run on system nodes
  node-role.kubernetes.io/system: "system"
rbac:
  create: true
sslCertHostPath: /etc/kubernetes/pki/ca.crt
podAnnotations:
  iam.amazonaws.com/role: arn:aws:iam::${aws_account_id}:role/${eks_cluster_name}-cluster-autoscaler

