---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fix-efs-file-permissions-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-efs-file-permissions
spec:
  template:
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["chmod",  "-R", "777", "/volumes/efs",]
          volumeMounts:
          - mountPath: /volumes/efs
            name: efs
      restartPolicy: Never
      volumes:
      - name: efs
        persistentVolumeClaim:
          claimName: fix-efs-file-permissions-pv-claim
  backoffLimit: 1