apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-prometheus-operator-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs_fs_id}