prometheus:
  prometheusSpec:
    retention: 30d
    retentionSize: 9GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi