prometheus:
  prometheusSpec:
    retention: 30d
    retentionSize: 9GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: efs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
        selector:
          matchLabels:
            app: prometheus